### ISSUE TITLE
Optifine Incompatibility

### ISSUE THREAD

**Issue by CruaverVoidDrake** [uyjulian/MinecraftX-RAY#7] opened 2017-05-13 18:42 UTC
Simply put the program crashes if you have optifine installed as well.
Specifics: All the 1.11.2 versions of optifine are incompatible.

**Comment by uyjulian** [comment] 2017-05-13 22:36
This is a known issue.

**Comment by CruaverVoidDrake** [comment] 2017-05-13 22:39
Alright, hope you can get that one fixed soon enough. It's useful for seeing easter egg redstone in server spawns.

**Comment by Codingale** [comment] 2017-05-18 02:39
Is there any version of this or Optifine that do not cause conflicts?

**Comment by CruaverVoidDrake** [comment] 2017-05-18 03:09
Not to my knowledge, I tried with the latest sets. It is possible that earlier versions work but I believe the problem is with the xray mod not optifine. After all the majority of issues involved the rendering of blocks.

**Comment by Codingale** [comment] 2017-05-18 08:28
I am assuming it's the new hook that he's been using.

**Comment by CruaverVoidDrake** [comment] 2017-05-18 08:30
Could be, I am not one for mod code, I'm better at command block code. Of course I don't think it was working last time, which I think was because I had the wrong version. It may also have something to do with Optifine's rendering optimization in the settings that he may not have on. So for all we know it doesn't work on a specific setting like fast quality or VBO off.

**Comment by uyjulian** [comment] 2017-05-18 10:07
The problem is both this mod / optifine.
They both hook into the rendering code, so that's why a conflict is occurring.

**Comment by Codingale** [comment] 2017-05-18 21:24
Mhm, is the a benefit to doing it this way vs the old way? I recall using both before with no issues.

**Comment by uyjulian** [comment] 2017-05-18 21:27
The old way uses Block.shouldSideBeRendered.

I looked into the hook of another X-ray mod, and it hooked in BlockModelRenderer. I decided to used that hook in my mod. This also allows me to adjust the brightness without a separate mod.

I'm going to ask Mumfrey how to apply a fallback mixin if one fails, later.

**Comment by Codingale** [comment] 2017-05-19 01:13
I didn't mind using Gamma bright, it was actually preferred since I use it for redstone and gamma bright effects all blocks where as the Xray doesn't brighten redstone.

**Comment by CruaverVoidDrake** [comment] 2017-05-19 01:27
Same, xray is super useful for hidden redstoners. I also miss ichun's morph mod because I could actually follow the redstone and do it in one block tall areas.

**Comment by uyjulian** [comment] 2017-07-15 23:44
Fixed in v1.0.1
Closing

**Closed by uyjulian** 2017-07-15 23:44 UTC
